### ISSUE TITLE
Want some cleanup? 

### ISSUE THREAD

**Issue by eduncan911** [skeeto/passphrase2pgp#3]
Love this project!  I've been wanting to get away from protecting my pgp keys for years, as I've felt vulnerable to attacks and stealing of it.  QubesOS has an awesome "split-pgp" feature i use on other systems, and this tool may could be adapted for it (with a bash script). 

Oh, and welcome to Golang!  I wanted to ask if you wanted some help cleaning up the code?  As I open it, my linters and parsers went insane!  Lol

**Comment by skeeto** [comment]
I'd never heard of Split GPG. Interesting idea.

https://www.qubes-os.org/doc/split-gpg/

As I worked, I'd been running goimports (routinely) and golint 
(occasionally). I see a few minor things slipped by, which I just fixed. 
What other issues are you seeing? What are these other linters?

**Comment by eduncan911** [comment]
Yeah, the split gpg feature basically stores your keys in an air-gapped "vault" VM on Xen, with the latest CVE patches and some protected memory tunneling for communications between VMs.

It may have been my self, as since I've upgraded the tooling locally things are better.
