### ISSUE TITLE
Bump version in code

### ISSUE THREAD

**Issue by TeddyDD** [skeeto/passphrase2pgp#6]
It's currently hardcoded to 0.1.0 :wink: 

Also  I'd change type of version from const to string so it can be overridden by ldflags -X

https://github.com/skeeto/passphrase2pgp/blob/a0f1ceb4b7613aa8cd82137c20ff5d3cd3cb8396/passphrase2pgp.go#L36

**Comment by skeeto** [comment]
Doh, thanks! Released v1.0.1 with this corrected.
